# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - '*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Runs a single command using the runners shell
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: npm install, build
        run: npm install && npm run build

      - name: Copy Dir
        run: mv ./public ./wordparty

      # Runs a set of commands using the runners shell
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          type: 'zip'
          path: 'wordparty'
          filename: 'wordparty.zip'

      - name: GitHub Releases
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: wordparty.zip
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
